---
title: "Tutorial on describing of French municipalities"
format: html
---


# Aim

The goal is to explore BD CARTO for the department of Landes (40), in Gironde (33), in Charente Maritime (17).

# 0. Setting-up

### Install and load packages


### Download data

The BD CARTO needs to be downloaded and stored in `data/` folder.
Aldo Vegetation index from COPERNICUS
https://land.copernicus.eu/en/products/vegetation?tab=vegetation_phenology_and_productivity_parameters
https://sdi.eea.europa.eu/catalogue/copernicus/api/records/977e4bb8-407f-48ec-b4c4-403bca5a6a3b?language=all

```{r}
# set data directory
datadir <- here::here("data")
if (!dir.exists(datadir)) {
  dir.create(
    path = datadir,
    showWarnings = FALSE,
    recursive = TRUE
  )
}

options(timeout = 1500)

dep <- c("017", "033", "040")
base_url <- "https://data.geopf.fr/telechargement/download/BDCARTO/BDCARTO_5-0_TOUSTHEMES_SHP_LAMB93_DXXX_2025-03-15/BDCARTO_5-0_TOUSTHEMES_SHP_LAMB93_DXXX_2025-03-15.7z"
for (i in dep) {
  diri <- paste0("BDCARTO_5-0_TOUSTHEMES_SHP_LAMB93_D", i, "_2025-03-15")
  if (!dir.exists(here::here(datadir, diri))) {
    tempfile <- file.path(datadir, "temp_17.7z")
    download.file(gsub("XXX", i, base_url), tempfile, mode = "wb")
    # extract all
    archive::archive_extract(tempfile, dir = datadir)
    # remove archive
    file.remove(tempfile)
  }
}
```


# 1. Land cover


```{r}
#load all road network
lc_files <- list.files(datadir, "OCCUPATION_DU_SOL.shp", recursive = TRUE)

lc <- vect()
for (f in lc_files) {
  lcf <- terra::vect(here::here(datadir, f))
  lc <- rbind(lc, lcf)
}
```


# 2. Road network


```{r}
#load all road network
road_files <- list.files(datadir, "TRONCON_DE_ROUTE.shp", recursive = TRUE)

road <- vect()
for (f in road_files) {
  # read file f
  roadf <- terra::vect(here::here(datadir, f))
  # aggregate to road
  road <- rbind(road, roadf)
}

mapview::mapview(road)
```


# 2. Road network


```{r}
#load all road network
road_files <- list.files(datadir, "TRONCON_DE_ROUTE.shp", recursive = TRUE)

road <- vect()
for (f in road_files) {
  # read file f
  roadf <- terra::vect(here::here(datadir, f))
  # aggregate to road
  road <- rbind(road, roadf)
}

mapview::mapview(road)
```